### PR TITLE
allow configuring the TLS and LDAP config secret name

### PR DESCRIPTION
**Pull request by NiklasRosenstein**

### CODE REVIEW

**Comment by alfespa17** [comment]
Hello @NiklasRosenstein 

Could you update the helm chart version number please:

https://github.com/AzBuilder/terrakube-helm-chart/blob/main/charts/terrakube/Chart.yaml#L18

**Comment by NiklasRosenstein** [comment]
@alfespa17 I've bumped it to 3.4.1, or would you rather this be a 3.5.0?

**Review by alfespa17 — APPROVED** [review]
It looks good now 👍

**Comment by alfespa17** [comment]
Thank you for your contribution @NiklasRosenstein

**Pull request merged**
